# Generated by Django 3.2.3 on 2021-05-20 06:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('subtitle', models.CharField(max_length=20)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('baseitems_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.baseitems')),
                ('publish_date', models.DateField(verbose_name=django.utils.timezone.now)),
                ('image', models.ImageField(default='new.png', upload_to='nosequeponer')),
            ],
            bases=('news.baseitems',),
        ),
    ]
