# Generated by Django 3.2.3 on 2021-05-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_new_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(default='static/news/images/new.jpg', upload_to='media/'),
        ),
    ]
