# Generated by Django 3.2.3 on 2021-05-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_new_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='publish_date',
            field=models.DateField(),
        ),
    ]
