# Generated by Django 3.2.3 on 2021-05-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_new_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(default='static/news/images/new.png', upload_to='media/'),
        ),
    ]
